checks:pylint:
  before_script:
  - pip3 install --quiet -r ci/requirements.txt
  script:
  - python3 -m pylint --rcfile=.pylintrc qubespdfconverter
  stage: checks
include:
- file: /r4.1/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.1/gitlab-dom0.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.1/gitlab-vm.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-vm.yml
  project: QubesOS/qubes-continuous-integration
